# Generated by Django 3.0.3 on 2020-03-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_managment', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this perticular book across whole Library', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WaitingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_managment.Waiting')),
            ],
        ),
        migrations.AddField(
            model_name='waiting',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_managment.BookInstance'),
        ),
        migrations.AddField(
            model_name='waiting',
            name='user',
            field=models.ManyToManyField(through='book_managment.WaitingTime', to=settings.AUTH_USER_MODEL),
        ),
    ]
