# Generated by Django 3.0.3 on 2020-04-01 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_managment', '0003_auto_20200327_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('bookinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_managment.BookInstance')),
            ],
        ),
    ]
